version: '4.32.0'

services:

  redis:
    image: redis:alpine

  django:
    container_name: django
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8001:8000
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: celery --app=assignment worker -l INFO
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis