# Generated by Django 5.0.7 on 2024-07-31 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigeneration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media', verbose_name='image'),
            preserve_default=False,
        ),
    ]
